### ISSUE TITLE
Reset in GUI does nothing...

### ISSUE THREAD

**Issue by Lewiscowles1986** [andydotxyz/sudokgo#3]
So I was being a smart-*** and I solved the puzzle then hit reset; expecting that to reset the board to the original state, like it might in a web-form when reset is pressed.

Seems like the button calls reset, which calls refresh.

Maybe the naming is off, but locally I've just deleted the method and widget.

LMK how you'd like to proceed; happy to PR something.

**Comment by andydotxyz** [comment]
Ah, the reset button works for me, but perhaps this changes after verifying a complete solution?

**Comment by Lewiscowles1986** [comment]
So this is prior to verifying the complete solution. It's solved, but not verified. I Realize that verification uses solve; which I believe might be another bug, or area of limited flexibility in the algorithm.

Scenario 1: Working as expected

* ![New Game](https://user-images.githubusercontent.com/2605791/147646981-69a824c1-bc20-452d-bc48-4016ed21e06f.png)
![Enter a cell value](https://user-images.githubusercontent.com/2605791/147646950-144ea719-c501-466d-b65c-da4a286343a9.png)
![Reset](https://user-images.githubusercontent.com/2605791/147646989-8c84440a-f92e-40ca-9323-9262e61e9870.png)

Scenario 2: After using solve; then using reset, the underlying game state, as well as display state has been changed irrevocably.

* ![New Game](https://user-images.githubusercontent.com/2605791/147646981-69a824c1-bc20-452d-bc48-4016ed21e06f.png)
* ![Solve Puzzle](https://user-images.githubusercontent.com/2605791/147647137-6e9990e1-572b-48cc-b481-8ac88a73d36e.png)
* ![Attempt Reset](https://user-images.githubusercontent.com/2605791/147647178-e05a375f-f267-4e31-a4c3-71691fdab32c.png)


Scenario 3: I use verify, not solve to reset after one or more wrong entries...

* ![New Game](https://user-images.githubusercontent.com/2605791/147648945-c1faede4-ca67-4eda-94d5-f81560e9893e.png)
* ![Make Mistake](https://user-images.githubusercontent.com/2605791/147648994-26259ea7-9743-4ed4-a4ee-c9913646bda7.png)
* ![Reset](https://user-images.githubusercontent.com/2605791/147648945-c1faede4-ca67-4eda-94d5-f81560e9893e.png)
* ![Fill in grid with obtusely incorrect values](https://user-images.githubusercontent.com/2605791/147649152-f4473a71-d3be-440a-9bcc-fd2836bfb53a.png)
* ![Reset still works](https://user-images.githubusercontent.com/2605791/147648945-c1faede4-ca67-4eda-94d5-f81560e9893e.png)
* ![Fill in grid with obtusely incorrect values](https://user-images.githubusercontent.com/2605791/147649152-f4473a71-d3be-440a-9bcc-fd2836bfb53a.png)
* ![Attempt to verify known incorrect solution](https://user-images.githubusercontent.com/2605791/147649579-0eff6b08-4e0b-4f17-882e-0b1cc444b0d3.png)
8 ![Reset now shows me the right answers](https://user-images.githubusercontent.com/2605791/147649625-f13d5b1b-fc85-4676-806f-a506ae8ac24e.png)

**Comment by Lewiscowles1986** [comment]
Ah, I see now there was a fix submitted that indeed fixes this 👍

**Comment by andydotxyz** [comment]
Things don't normally get fixed that fast, but I happened to be on my laptop at the time :)
